# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ObserviqOtelCollectorAT100 < Formula
  desc ""
  homepage "https://github.com/observIQ/observiq-otel-collector"
  version "1.0.0"
  license "Apache 2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/observIQ/observiq-otel-collector/releases/download/v1.0.0/observiq-otel-collector-v1.0.0-darwin-amd64.tar.gz", :using => CurlDownloadStrategy
      sha256 "7be8eb43d9ed2b7fb0705a71b8d9f61a9c2d8eb3a552aaea8a43d6cf81d16f8c"

      def install
        bin.install "observiq-otel-collector"
        prefix.install "LICENSE", "config.yaml", "VERSION.txt", "logging.yaml"
        prefix.install Dir["plugins"]
        lib.install "opentelemetry-java-contrib-jmx-metrics.jar"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/observIQ/observiq-otel-collector/releases/download/v1.0.0/observiq-otel-collector-v1.0.0-darwin-arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "2e4a29d9be8b4c93ae1308141c9642329c7ef130455e811970f514d03bff490b"

      def install
        bin.install "observiq-otel-collector"
        prefix.install "LICENSE", "config.yaml", "VERSION.txt", "logging.yaml"
        prefix.install Dir["plugins"]
        lib.install "opentelemetry-java-contrib-jmx-metrics.jar"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/observIQ/observiq-otel-collector/releases/download/v1.0.0/observiq-otel-collector-v1.0.0-linux-arm.tar.gz", :using => CurlDownloadStrategy
      sha256 "8b79ff95f8e6584fe3e5cfe2838672a453f2c02d814187abee58104aec126379"

      def install
        bin.install "observiq-otel-collector"
        prefix.install "LICENSE", "config.yaml", "VERSION.txt", "logging.yaml"
        prefix.install Dir["plugins"]
        lib.install "opentelemetry-java-contrib-jmx-metrics.jar"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/observIQ/observiq-otel-collector/releases/download/v1.0.0/observiq-otel-collector-v1.0.0-linux-amd64.tar.gz", :using => CurlDownloadStrategy
      sha256 "66b1a7e51d94cbf98d563a813bb571c8813417a33777859c863f6fb14c95f420"

      def install
        bin.install "observiq-otel-collector"
        prefix.install "LICENSE", "config.yaml", "VERSION.txt", "logging.yaml"
        prefix.install Dir["plugins"]
        lib.install "opentelemetry-java-contrib-jmx-metrics.jar"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/observIQ/observiq-otel-collector/releases/download/v1.0.0/observiq-otel-collector-v1.0.0-linux-arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "cb991673672e69a997b6826b3cd479eec8671e1b79fda6c3a39bf09b41205611"

      def install
        bin.install "observiq-otel-collector"
        prefix.install "LICENSE", "config.yaml", "VERSION.txt", "logging.yaml"
        prefix.install Dir["plugins"]
        lib.install "opentelemetry-java-contrib-jmx-metrics.jar"
      end
    end
  end

  def caveats; <<~EOS
    ****************************************************************
    The configuration file that is run by the service is located at #{prefix}/config.yaml.

    If you are configuring a logreceiver the plugin directory is located at #{prefix}/plugins.
    ****************************************************************

    ****************************************************************
    Below are services commands to run to manage the collector service.
    If you wish to run the collector at boot prefix these commands with sudo
    otherwise the service will run at login.

    To start the collector service run:

      brew services start observiq/observiq-otel-collector/observiq-otel-collector@1.0.0

    To stop the collector service run:

      brew services stop observiq/observiq-otel-collector/observiq-otel-collector@1.0.0

    To restart the collector service run:

      brew services restart observiq/observiq-otel-collector/observiq-otel-collector@1.0.0
    ****************************************************************

    ****************************************************************
    To uninstall the collector and its dependencies run the following commands:

        brew services stop observiq/observiq-otel-collector/observiq-otel-collector@1.0.0
        brew uninstall observiq/observiq-otel-collector/observiq-otel-collector@1.0.0
        launchctl remove com.observiq.collector

        # If you moved the opentelemetry-java-contrib-jmx-metrics.jar
        sudo rm /opt/opentelemetry-java-contrib-jmx-metrics.jar

    ****************************************************************
  EOS
  end

  plist_options :startup => false

  service do
    run [opt_bin/"observiq-otel-collector", "--config", opt_prefix/"config.yaml", "--logging", opt_prefix/"logging.yaml", "--manager", opt_prefix/"manager.yaml"]
    environment_variables OIQ_OTEL_COLLECTOR_HOME: opt_prefix
    keep_alive true
  end
end
