# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ObserviqOtelCollector < Formula
  desc ""
  homepage "https://github.com/observIQ/observiq-otel-collector"
  version "0.5.0"
  license "Apache 2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/observIQ/observiq-otel-collector/releases/download/v0.5.0/observiq-otel-collector-v0.5.0-darwin-amd64.tar.gz", :using => CurlDownloadStrategy
      sha256 "7bad2ed17c148fb3ede6c21363c50f32f1560822db55785f38ff107a464b6c07"

      def install
        bin.install "observiq-otel-collector"
        prefix.install "LICENSE", "config.yaml"
        prefix.install Dir["plugins"]
        lib.install "opentelemetry-java-contrib-jmx-metrics.jar"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/observIQ/observiq-otel-collector/releases/download/v0.5.0/observiq-otel-collector-v0.5.0-darwin-arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "587533cc1bf4ea56229a3c1d36a766951487b86c24cd741b03be8f4575caf044"

      def install
        bin.install "observiq-otel-collector"
        prefix.install "LICENSE", "config.yaml"
        prefix.install Dir["plugins"]
        lib.install "opentelemetry-java-contrib-jmx-metrics.jar"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/observIQ/observiq-otel-collector/releases/download/v0.5.0/observiq-otel-collector-v0.5.0-linux-arm.tar.gz", :using => CurlDownloadStrategy
      sha256 "980a8beaad56b0035b7abb13dea92c8059822d342292a2a63e11061b4508b852"

      def install
        bin.install "observiq-otel-collector"
        prefix.install "LICENSE", "config.yaml"
        prefix.install Dir["plugins"]
        lib.install "opentelemetry-java-contrib-jmx-metrics.jar"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/observIQ/observiq-otel-collector/releases/download/v0.5.0/observiq-otel-collector-v0.5.0-linux-amd64.tar.gz", :using => CurlDownloadStrategy
      sha256 "eb75425047798de0b82965f4aec3393af73ad74b7e75852b743516ff6d25b682"

      def install
        bin.install "observiq-otel-collector"
        prefix.install "LICENSE", "config.yaml"
        prefix.install Dir["plugins"]
        lib.install "opentelemetry-java-contrib-jmx-metrics.jar"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/observIQ/observiq-otel-collector/releases/download/v0.5.0/observiq-otel-collector-v0.5.0-linux-arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "4670d27a294f213d383724b7794fe93e1d4846fa873e42d228e7b67ab49a1a82"

      def install
        bin.install "observiq-otel-collector"
        prefix.install "LICENSE", "config.yaml"
        prefix.install Dir["plugins"]
        lib.install "opentelemetry-java-contrib-jmx-metrics.jar"
      end
    end
  end

  def caveats; <<~EOS
    ****************************************************************
    The configuration file that is run by the service is located at #{prefix}/config.yaml.

    If you are configuring a logreceiver the plugin directory is located at #{prefix}/plugins.
    ****************************************************************

    ****************************************************************
    Below are services commands to run to manage the collector service.
    If you wish to run the collector at boot prefix these commands with sudo
    otherwise the service will run at login.

    To start the collector service run:

      brew services start observiq/observiq-otel-collector/observiq-otel-collector

    To stop the collector service run:

      brew services stop observiq/observiq-otel-collector/observiq-otel-collector

    To restart the collector service run:

      brew services restart observiq/observiq-otel-collector/observiq-otel-collector
    ****************************************************************

    ****************************************************************
    To uninstall the collector and its dependencies run the following commands:

        brew services stop observiq/observiq-otel-collector/observiq-otel-collector
        brew uninstall observiq/observiq-otel-collector/observiq-otel-collector
        launchctl remove com.observiq.collector

        # If you moved the opentelemetry-java-contrib-jmx-metrics.jar
        sudo rm /opt/opentelemetry-java-contrib-jmx-metrics.jar

    ****************************************************************
  EOS
  end

  plist_options :startup => false

  def plist; <<~EOS
    <?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>

    <key>Label</key>
    <string>com.observiq.collector</string>

    <key>ProgramArguments</key>
    <array>
      <string>#{bin}/observiq-otel-collector</string>
      <string>--config</string>
      <string>#{prefix}/config.yaml</string>
    </array>

    <key>RunAtLoad</key>
    <true/>

    <key>StandardErrorPath</key>
    <string>/tmp/observiq-otel-collector.log</string>

    <key>StandardOutPath</key>
    <string>/tmp/observiq-otel-collector.log</string>
  </dict>
</plist>

  EOS
  end
end
